### ISSUE TITLE
Loops should have <a reliable, unique index>

### ISSUE THREAD

**Issue by franz-josef-kaiser** [score-framework/js.dom#10]
As seen in the [`js.dom.children()` function](https://github.com/score-framework/js.dom/blob/ddafb6189c3bbf536bef100b271b39edd491fe3b/dom.js#L145-L156), we currently use a loop that reuses indices [from object properties](https://github.com/score-framework/js.dom/blob/ddafb6189c3bbf536bef100b271b39edd491fe3b/dom.js#L49). As those a are shared across methods, they might not be what we expect.
#### Acceptance criteria
- [ ] Each functions loop resets their index by using `var`
- [ ] Unit tests prove that nesting does not harm or alter the current loops index in its scope

**Comment by soulmerge** [comment]
This should not be an issue unless another function is called in the loop body (as was the case with forEach() in #9). If this is the cause of some unexpected behaviour, we would need a demonstration (preferebly in the form of a unit test).

**Comment by franz-josef-kaiser** [comment]
Closing as _too localized_.
