### ISSUE TITLE
Problem in Linux webkits browsers (Midori, Luakit)

### ISSUE THREAD

**Issue by tyriis** [score-framework/js.dom#4]
when passing a query selector string to score.dom in webkit based browsers under linux f.e. Midori or Luakit i got the following error:

TypeError: Requested prototype of a value that is not an object.

```
dom = function(arg) {
    result = Object.create(dom.proto);
        if (arg) {
-->         if (Object.getPrototypeOf(arg) == dom.proto || Array.isArray(arg)) {

```

**Comment by soulmerge** [comment]
The code seems to be from an earlier version of score.dom, could you retry with the latest (0.0.7)?

**Comment by tyriis** [comment]
works
